### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by tuanlaceo** [geyuying/PF-AFN#46]
Hi, Thank about your project
I 'ad run test.py .
But I got runtime error like that: 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\AT\.conda\envs\tryon\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\AT\.conda\envs\tryon\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\AT\.conda\envs\tryon\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\AT\.conda\envs\tryon\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\AT\.conda\envs\tryon\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\AT\.conda\envs\tryon\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\AT\.conda\envs\tryon\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\AT\Desktop\GAN\CUDA10\PF-AFN\PF-AFN_test\test.py", line 40, in <module>
    for i, data in enumerate(dataset, start=epoch_iter):
  File "C:\Users\AT\.conda\envs\tryon\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\AT\.conda\envs\tryon\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()
  File "C:\Users\AT\.conda\envs\tryon\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\AT\.conda\envs\tryon\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\AT\.conda\envs\tryon\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\AT\.conda\envs\tryon\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\AT\.conda\envs\tryon\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\AT\.conda\envs\tryon\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "C:\Users\AT\.conda\envs\tryon\lib\site-packages\torch\utils\data\dataloader.py", line 511, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "C:\Users\AT\.conda\envs\tryon\lib\multiprocessing\queues.py", line 105, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 40, in <module>
    for i, data in enumerate(dataset, start=epoch_iter):
  File "C:\Users\AT\.conda\envs\tryon\lib\site-packages\torch\utils\data\dataloader.py", line 576, in __next__
    idx, batch = self._get_batch()
  File "C:\Users\AT\.conda\envs\tryon\lib\site-packages\torch\utils\data\dataloader.py", line 553, in _get_batch
    success, data = self._try_get_batch()
  File "C:\Users\AT\.conda\envs\tryon\lib\site-packages\torch\utils\data\dataloader.py", line 519, in _try_get_batch
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 10200) exited unexpectedly

#I tried to change worker =0 but no work
# pls help. Thank much

**Comment by hjralyc** [comment]
I also encountered the same problem

**Comment by hjralyc** [comment]
I found the problem because os.fork() is not supported under windows10 64-bit version.
u need to add this in test.py
"if __name__ == '__main__':
    ..."

**Comment by tuanlaceo** [comment]
@hjralyc  Thank ^^

**Comment by fun-code-ai** [comment]
> I found the problem because os.fork() is not supported under windows10 64-bit version. u need to add this in test.py "if **name** == '**main**': ..."

hi ,i do just same with you ,but i have new issues, such as:
D:\Anaconda\envs\tryon\lib\site-packages\torchvision\transforms\transforms.py:209: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Traceback (most recent call last):
  File "C:/Users/小地瓜/Desktop/PF-AFN-main/PF-AFN_test/test.py", line 54, in <module>
    flow_out = warp_model(real_image.cuda(), clothes.cuda())
  File "D:\Anaconda\envs\tryon\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\小地瓜\Desktop\PF-AFN-main\PF-AFN_test\models\afwm.py", line 192, in forward
    cond_pyramids = self.cond_FPN(self.cond_features(cond_input)) # maybe use nn.Sequential
  File "D:\Anaconda\envs\tryon\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\小地瓜\Desktop\PF-AFN-main\PF-AFN_test\models\afwm.py", line 73, in forward
    x = encoder(x)
  File "D:\Anaconda\envs\tryon\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\tryon\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "D:\Anaconda\envs\tryon\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\小地瓜\Desktop\PF-AFN-main\PF-AFN_test\models\afwm.py", line 47, in forward
    return self.block(x)
  File "D:\Anaconda\envs\tryon\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\tryon\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "D:\Anaconda\envs\tryon\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\tryon\lib\site-packages\torch\nn\modules\conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

Process finished with exit code 1
cloud you tell how i do

**Comment by b0nl** [comment]
Have you found a solution to the above issue please?

RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

I'm getting this problem too.

**Comment by fun-code-ai** [comment]
Yes I use cloud service ,my computer couldn’t support gpa---- Replied Message ***@***.***>Date07/06/2022 20:29 ***@***.***> ***@***.******@***.***>SubjectRe: [geyuying/PF-AFN] RuntimeError (#46)
Have you found a solution to the above issue please?
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
I'm getting this problem too.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/geyuying/PF-AFN/issues/46#issuecomment-1176162453",
"url": "https://github.com/geyuying/PF-AFN/issues/46#issuecomment-1176162453",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
