### ISSUE TITLE
Type Error while loading data from train_dense pose 

### ISSUE THREAD

**Issue by SumanthJain2998** [geyuying/PF-AFN#49]
@geyuying  ***Hello, This is a wonderful repository you have provided us.  I'm trying to train the Network on google colab, I was able to do the necessary modifications in code to bring it down to a single GPU. But there's a type mismatch while it runs iteration through .npy file formats. It's being perceived as int object. I request you to help me resolve the issue*** 

/usr/local/lib/python3.7/site-packages/torchvision/transforms/transforms.py:281: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
Traceback (most recent call last):
  File "train_PBAFN_stage1.py", line 79, in <module>
    for i, data in enumerate(train_loader):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/PF-AFN/PF-AFN_train/data/aligned_dataset.py", line 108, in __getitem__
    dense_mask = transform_A(dense_mask)
  File "/usr/local/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/usr/local/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 430, in __call__
    return self.lambd(img)
  File "/content/PF-AFN/PF-AFN_train/data/base_dataset.py", line 64, in <lambda>
    transform_list.append(transforms.Lambda(lambda img: __scale_width(img, opt.loadSize, method)))
  File "/content/PF-AFN/PF-AFN_train/data/base_dataset.py", line 98, in __scale_width
    ow, oh = img.size
TypeError: cannot unpack non-iterable int object

 ** Thank You**

**Comment by SumanthJain2998** [comment]
It got resolved, I had to do the changes in the Training script

**Comment by puhuk** [comment]
@SumanthJain2998 
Hi, I have same issues, Could you say how you resolve this.
