### ISSUE TITLE
Train issue

### ISSUE THREAD

**Issue by LeoMyMe** [geyuying/PF-AFN#86]
![image](https://github.com/geyuying/PF-AFN/assets/108519487/f205530d-7b8a-48a8-9a3c-8d295a7f8ba9)
Why warped_cloth and it's mask missing after 294000.

And there is also an another problem that I must change the train code.↓
Traceback (most recent call last):
  File "train_PBAFN_stage1.py", line 116, in <module>
    loss_vgg = criterionVGG(x_all[num], cur_person_clothes.cuda())
  File "C:\Users\Leo\anaconda3\envs\PMC2D\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Leo\Desktop\PF-AFN\PF-AFN_train\models\networks.py", line 164, in forward
    x_vgg, y_vgg = self.vgg(x), self.vgg(y)
  File "C:\Users\Leo\anaconda3\envs\PMC2D\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Leo\Desktop\PF-AFN\PF-AFN_train\models\networks.py", line 150, in forward
    h_relu5 = self.slice5(h_relu4)
  File "C:\Users\Leo\anaconda3\envs\PMC2D\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Leo\anaconda3\envs\PMC2D\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "C:\Users\Leo\anaconda3\envs\PMC2D\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Leo\anaconda3\envs\PMC2D\lib\site-packages\torch\nn\modules\pooling.py", line 166, in forward
    return F.max_pool2d(input, self.kernel_size, self.stride,
  File "C:\Users\Leo\anaconda3\envs\PMC2D\lib\site-packages\torch\_jit_internal.py", line 485, in fn
    return if_false(*args, **kwargs)
  File "C:\Users\Leo\anaconda3\envs\PMC2D\lib\site-packages\torch\nn\functional.py", line 782, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: Given input size: (512x2x1). Calculated output size: (512x1x0). Output size is too small

**Comment by LeoMyMe** [comment]
--niter 100 --niter_decay 100

**Comment by LeoMyMe** [comment]
--niter 100 --niter_decay 100

**Comment by Rockdow** [comment]
@LeoMyMe Hi, I'm facing the same problem. Have you found out the reason?

**Comment by diixo** [comment]
the same problem
